### ISSUE TITLE
HapB3 alternate name

### ISSUE THREAD

**Issue by aroon-color** [0xTCG/aldy#79]
Hi Ibrahim (@inumanag),

It appears that Aldy presents DPYD `*HapB3` as both `*HapB3` when it's the only allele present or as the alt_name, `HapB3` (no `*`) when in combination with another allele/variant. Should this also be `label: DPYD*HapB3` to match the rest of the star alleles?

https://github.com/0xTCG/aldy/blob/98ab065a79a3caf875aa37867122bddeabb4cef6/aldy/resources/genes/dpyd.yml#L91

We were also wondering if there should be another definition for the haplotype w/o `[352197, G>A, rs56038477, intronic]`:

```
  DPYD*HapB3:
    pharmvar: https://www.pharmvar.org/haplotype/1077
    activity: decreased function
    label: DPYD*HapB3
    mutations:
    - [346167, C>G, rs75017182, intronic]
```
in line with https://app.getbeamer.com/pharmvar1749/en/database-updated-to-version-6010

cc @jeroenvdakker
